name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            cd ~/Notebook

            git pull origin main

            npm install --legacy-peer-deps

            pm2 restart notebook-server || pm2 start server.js --name notebook-server

            pm2 restart notebook-worker || pm2 start worker.js --name notebook-worker

            pm2 save